# Workflow para construir e publicar um projeto React no GitHub Pages
name: Deploy React to GitHub Pages

on:
  # Aciona o workflow em push para a branch principal
  push:
    branches: ["main"]

  # Permite rodar manualmente o workflow pela aba de Actions
  workflow_dispatch:

# Define as permissões necessárias para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Garante que apenas um deploy seja feito por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construção
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura a versão do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala as dependências
      - name: Install dependencies
        run: npm install

      # Constrói o projeto
      - name: Build project
        run: npm run build

      # Faz upload dos arquivos de build como um artefato
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  # Job de deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Faz o deploy do artefato para o GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
